export default [
  {
    id: "q1",
    text: "¿Respetas el semáforo en rojo incluso cuando no hay vigilancia?",
    type: "radio",
    options: [
      { value: "yes", label: "Sí, siempre" },
      { value: "sometimes", label: "A veces" },
      { value: "no", label: "No, si no hay tránsito" },
    ],
    weight: 10,
    correctAnswers: ["yes"],
  },
  {
    id: "q2",
    text: "¿Cedes el paso en un cruce sin señalización?",
    type: "radio",
    options: [
      { value: "yes", label: "Sí, priorizo la precaución" },
      { value: "no", label: "No, avanzo sin precaución" },
    ],
    weight: 10,
    correctAnswers: ["yes"],
  },
  {
    id: "q3",
    text: "¿Reducís la velocidad al transitar cerca de una escuela?",
    type: "radio",
    options: [
      { value: "yes", label: "Sí, siempre reduzco" },
      { value: "no", label: "No" },
    ],
    weight: 10,
    correctAnswers: ["yes"],
  },
  {
    id: "q4",
    text: "¿Respetas el paso de peatones incluso si no está marcado?",
    type: "radio",
    options: [
      { value: "yes", label: "Sí, respeto a los peatones" },
      { value: "no", label: "No" },
    ],
    weight: 10,
    correctAnswers: ["yes"],
  },
  {
    id: "q5",
    text: "¿Consideras correcto estacionarte en doble fila?",
    type: "radio",
    options: [
      { value: "no", label: "No, está mal" },
      { value: "yes", label: "Sí, si es breve" },
    ],
    weight: 10,
    correctAnswers: ["no"],
  },
  {
    id: "q6",
    text: "¿Cedes el paso a ambulancias en tráfico?",
    type: "radio",
    options: [
      { value: "yes", label: "Sí, inmediatamente" },
      { value: "no", label: "No, continúo" },
    ],
    weight: 10,
    correctAnswers: ["yes"],
  },
  {
    id: "q7",
    text: "¿Crees correcto que una motocicleta use la acera para evitar tráfico?",
    type: "radio",
    options: [
      { value: "no", label: "No, es peligroso" },
      { value: "yes", label: "Sí, si es más rápido" },
    ],
    weight: 10,
    correctAnswers: ["no"],
  },
  {
    id: "q8",
    text: "¿Cómo actúas en una rotonda sin señalización?",
    type: "radio",
    options: [
      { value: "yield", label: "Cedo preferencia y paso con precaución" },
      { value: "rush", label: "Aprovecho y paso rápido" },
    ],
    weight: 10,
    correctAnswers: ["yield"],
  },
  {
    id: "q9",
    text: "¿Respetas el flujo en calles estrechas con vehículos mal estacionados?",
    type: "radio",
    options: [
      { value: "yes", label: "Sí, conduzco con precaución" },
      { value: "no", label: "No presto atención" },
    ],
    weight: 10,
    correctAnswers: ["yes"],
  },
  {
    id: "q10",
    text: "¿Usas casco como pasajero o conductor de motocicleta?",
    type: "radio",
    options: [
      { value: "yes", label: "Sí, siempre" },
      { value: "sometimes", label: "A veces" },
      { value: "no", label: "Nunca" },
    ],
    weight: 10,
    correctAnswers: ["yes"],
  },
  {
    id: "q11",
    text: "¿Cedes el paso en zonas comerciales aunque no haya paso peatonal marcado?",
    type: "radio",
    options: [
      { value: "yes", label: "Sí, soy precavido" },
      { value: "no", label: "No" },
    ],
    weight: 10,
    correctAnswers: ["yes"],
  },
  {
    id: "q12",
    text: "¿Has circulado en moto en contra vía alguna vez?",
    type: "radio",
    options: [
      { value: "never", label: "No, nunca" },
      { value: "yes", label: "Sí, algunas veces" },
    ],
    weight: 10,
    correctAnswers: ["never"],
  },
  {
    id: "q13",
    text: "¿Atiendes llamadas mientras conduces?",
    type: "radio",
    options: [
      { value: "no", label: "No, nunca" },
      { value: "yes", label: "Sí, a veces" },
    ],
    weight: 10,
    correctAnswers: ["no"],
  },
  {
    id: "q14",
    text: "¿Usas cinturón incluso en asientos traseros?",
    type: "radio",
    options: [
      { value: "yes", label: "Sí, siempre" },
      { value: "no", label: "No" },
    ],
    weight: 10,
    correctAnswers: ["yes"],
  },
  {
    id: "q15",
    text: "Al ver cruzar a una persona mayor o un animal, ¿qué haces?",
    type: "radio",
    options: [
      { value: "slow", label: "Reduzco velocidad y cedo el paso" },
      { value: "ignore", label: "Sigo igual" },
    ],
    weight: 10,
    correctAnswers: ["slow"],
  },
  {
    id: "q16",
    text: "¿Te parece seguro transportar tres personas en moto?",
    type: "radio",
    options: [
      { value: "no", label: "No, está prohibido y es peligroso" },
      { value: "yes", label: "Sí, si es necesario" },
    ],
    weight: 10,
    correctAnswers: ["no"],
  },
  {
    id: "q17",
    text: "¿Forzarías el paso en una intersección en hora pico?",
    type: "radio",
    options: [
      { value: "no", label: "No, respeto los turnos" },
      { value: "yes", label: "Sí, para avanzar" },
    ],
    weight: 10,
    correctAnswers: ["no"],
  },
  {
    id: "q18",
    text: "¿Adelantas una guagua escolar recogiendo niños?",
    type: "radio",
    options: [
      { value: "stop", label: "Me detengo y espero" },
      { value: "pass", label: "Adelanto si puedo" },
    ],
    weight: 10,
    correctAnswers: ["stop"],
  },
]
